### ISSUE TITLE
Supper simple-obfs for shadowsocks

### ISSUE THREAD

**Issue by ghost** [moodyhunter/Plugins#1]
Since most of the SS airports have simple-obfs, I hope to support it in future versions. It’s hard work.

**Comment by database64128** [comment]
Ask your shitty "airport" to stop using the unsecure, deprecated simple-obfs. Keep in mind that you paid the "airport", not the developers.

**Comment by moodyhunter** [comment]
There's no shadowsocks plugin BTW.
